#!/usr/bin/env python
import os
import sys

import SCons.Variables
from methods import print_error
from SCons.Environment import Environment
from SCons.Script import ARGUMENTS, SConscript, Variables
from SCons.Script import HelpFunction as Help

libname = "interaction-plugin"
projectdir = "../../quest-world/addons/interaction_plugin_extension"
godot_cpp_path = "../godot-cpp"

localEnv = Environment(tools=["default"], PLATFORM="")
localEnv["api_version"] = "4.7"

# Build profiles can be used to decrease compile times.
# You can either specify "disabled_classes", OR
# explicitly specify "enabled_classes" which disables all other classes.
# Modify the example file as needed and uncomment the line below or
# manually specify the build_profile parameter when running SCons.

# localEnv["build_profile"] = "build_profile.json"

customs = ["custom.py"]
customs = [os.path.abspath(path) for path in customs]

opts: SCons.Variables.Variables = Variables(customs, ARGUMENTS)
opts.Update(localEnv)

Help(opts.GenerateHelpText(localEnv))

env = localEnv.Clone()

if not (os.path.isdir(godot_cpp_path) and os.listdir(godot_cpp_path)):
    print_error(f"""godot-cpp is not available within {godot_cpp_path}, as Git submodules haven't been initialized.
Run the following command to download godot-cpp:

    git submodule update --init --recursive""")
    sys.exit(1)

env: Environment = SConscript(
    f"{godot_cpp_path}/SConstruct", {"env": env, "customs": customs}
)

env.Append(CPPPATH=["src/"])
sources = env.Glob("src/*.cpp")

if env["target"] in ["editor", "template_debug"]:
    try:
        doc_data = env.GodotCPPDocData(
            "src/gen/doc_data.gen.cpp", source=env.Glob("doc_classes/*.xml")
        )
        sources.append(doc_data)
    except AttributeError:
        print("Not including class reference as we're targeting a pre-4.3 baseline.")

# .dev doesn't inhibit compatibility, so we don't need to key it.
# .universal just means "compatible with all relevant arches" so we don't need to key it.
suffix = (
    env["suffix"].replace(".dev", "").replace(".universal", "") if env["suffix"] else ""
)

lib_filename = "{}{}{}{}".format(
    env.subst("$SHLIBPREFIX"), libname, suffix, env.subst("$SHLIBSUFFIX")
)

library = env.SharedLibrary(
    "bin/{}/{}".format(env["platform"], lib_filename),
    source=sources,
)

copy = env.Install("{}/bin/{}/".format(projectdir, env["platform"]), library)

default_args = [library, copy]
env.Default(*default_args)
